name: OMEN CICD

on:
  push:
    branches: [ "ci-test" ]
  pull_request:
    branches: [ "ci-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: "osdev-omen:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max

  omen-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: List Docker images
      run: docker images

    - name: Setup buildenv
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src osdev-omen:latest make setup-gpt
  
    - name: Build GPT
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src osdev-omen:latest make gpt
