name: OMEN CICD

on:
  push:
    branches: [ "ci-test" ]
  pull_request:
    branches: [ "ci-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Pull Docker image
      run: | 
        docker pull aziabat/omen-osdev:latest
      
    - name: List images
      run: | 
        docker images
    - name: Setup buildenv
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src aziabat/omen-osdev:latest -c "make setup-gpt"
  
    - name: Build GPT
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src aziabat/omen-osdev:latest -c "make gpt"
